#!/bin/sh
#
# Simple build script that builds & copies pi-init2, as well as "appliance"
# files onto Raspberry Pi.
#
# Works for me on an Ubuntu system where a Raspberry Pi appears under
# /media/mattbee/boot but you may need to adjust.

export GOPATH=`pwd`
export GOOS=linux
export GOARCH=arm

FILES="cmdline.txt pi-init2 appliance"

go build -o pi-init2 projects.bytemark.co.uk/pi-init2 && \
  zip -r release.zip $FILES && \
  cp -a $FILES /media/$USER/boot && \
  umount /media/$USER/boot

