#!/bin/sh
MAC=$(cat /sys/class/net/wlan0/address)
echo
echo "Welcome to the Stanford Robotics Rapberry Pi distribution"
echo "The setup process is almost complete. You just need to register"
echo "the Pi with Stanford network to give it internet access. Go to"
echo "iprequest.stanford.edu and follow the onscreen instructions"
echo "As the wireless Hardware MAC address enter:"
echo
echo $MAC
echo
echo "Then reboot the Pi (sudo reboot) and run the following command"
echo
echo "bash ./install_packages.sh"
echo
